version: '3.7'

services:
  dbperson:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: person
      MYSQL_USER: userperson
      MYSQL_PASSWORD: pwdperson
    ports:
      - 5432:5432
    expose:
      - 5432