version: '3.7'
services:
  database-person:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: person
      MYSQL_USER: userperson
      MYSQL_PASSWORD: pwdperson
    container_name: db-person
    ports:
      - 5432:5432
    expose:
      -5432